### ISSUE TITLE
Basic experiment is missing control behavior

### ISSUE THREAD

**Issue by tfausak** [github/scientist#13]
I saw that y'all deprecated `dat-science` in favor of `scientist`. I want to update, but I immediately hit a roadblock. I couldn't get a basic experiment, like the one in the readme, to work. Here's what I tried:

``` rb
require 'scientist' # 0.0.3
Scientist::Default.new('experiment') do |e|
  e.use { true }
  e.try { true }
end.run
# Scientist::BehaviorMissing: experiment missing control behavior
```

Based on [the source](https://github.com/github/scientist/blob/v0.0.3/lib/scientist/experiment.rb#L158), I guessed that I might have to use `e.control` (like with `dat-science`) instead of `e.use`. That didn't work either. 

Am I doing something wrong?

**Comment by tfausak** [comment]
After looking at [the `science` mixin](https://github.com/github/scientist/blob/v0.0.3/lib/scientist/experiment.rb#L158) and the tests, I discovered that it doesn't work this way. I could get my experiment to work by removing the block.

``` rb
require 'scientist' # 0.0.3
e = Scientist::Default.new('experiment')
e.use { true }
e.try { true }
e.run
# => true
```

**Comment by zerowidth** [comment]
The `Scientist::Default` initializer doesn't take a block argument, whereas `Dat::Science::Experiment`'s did. The `Scientist#science` helper is what yields a new instance to a block:

```ruby
include Scientist
science "experiment" do |e|
  puts e.class.name # => Scientist::Default
  e.use { true }
  e.try { true }
end # => true
```

Let me know if you have any other questions!

**Comment by tfausak** [comment]
Can you update [the example in the readme](https://github.com/github/scientist/blob/6c0437def8e9b65b3ddc41a1d3546c55d2ad2418/README.md#how-do-i-do-science) to be correct?

**Comment by zerowidth** [comment]
Ah, yep. Will do.

**Comment by tfausak** [comment]
:+1: Thanks!
