### ISSUE TITLE
Ruby 2.1 compatibility still mentioned in the readme

### ISSUE THREAD

**Issue by nilbus** [github/scientist#14]
95c4beff7cc2ae8c3e611d7ed8b0e030a32d14ec removes the dependency on Ruby 2.1, right? Could you update that documented requirement at the bottom of the [readme](https://github.com/github/scientist/blob/master/README.md#hacking)? Is it now Ruby 1.9 compatible?

**Comment by zerowidth** [comment]
Scientist is ruby 1.9 compatible. I'll update the README, thanks for the reminder!
