### ISSUE TITLE
Allow setting raise_on_mismatch per Experiment

### ISSUE THREAD

**Issue by rsanheim** [github/scientist#21]
It would be really useful for a certain project I'm working on to be able to set the `raise_on_mismatch` setting at the Experiment level, instead of a class level attribute.  Something like:

```
science("my-experiment") do |e|
  e.raise_on_mismatches = true
  e.control {}
  e.candidate {}
end
```

What do you think?

**Comment by jesseplusplus** [comment]
:+1: Agreed this would be useful, and a fairly easy change I think.

**Comment by jbarnette** [comment]
This is done thanks to @tyamagu2, I'll close this issue when `1.0.0` drops.

**Comment by jbarnette** [comment]
Looks like we did this. :smile:
