### ISSUE TITLE
What do you call the high-level concept of scientist?

### ISSUE THREAD

**Issue by boxcleverliam** [github/scientist#243]
Scientist is _fantastic_ for Ruby development, but how would I find a similar library for other languages? I'm looking to do this in PHP and JS.

Is there a name for this technique or pattern of development? Having a control and a candidate and running both under load, to analyze the results - this is a pattern I have also used, but without good terminology to quickly communicate to others.

The Control / Candidate Pattern?
Candidate Driven Development?

If there is a common name for this, it would be good to add it to the README.

**Comment by AyeMinPhyo584** [comment]
_
![Uploading 17105079508555069581612421309779.jpg…]()
_

**Comment by zerowidth** [comment]
Not sure what I'd call it. "candidate driven development" or "measurement-based refactoring"? 

You can find a list of alternatives in the README, including a PHP implementation: https://github.com/github/scientist?tab=readme-ov-file#alternatives
