### ISSUE TITLE
Scientist for PHP

### ISSUE THREAD

**Issue by daylerees** [github/scientist#33]
Hi Github! Thanks for everything that you do for us!

Scientist looks amazing. Unfortunately, I'm somewhat attached to PHP still.

Don't worry though, I decided to port Scientist to PHP, and here it is:

https://github.com/daylerees/scientist

It's fairly similar, apart from the obvious quirks that arise from a difference in language.

I'd love it if you'd consider linking it as an alternative from your readme, and if not.. well.. thanks for the library anyway!

Have a great weekend.

Dayle.

**Comment by jbarnette** [comment]
@daylerees This is so cool! Thanks for the link. You're right, it's time for us to add an "Alternatives" section to the README.

**Comment by daylerees** [comment]
I could send a PR if it suits? Thanks :)

**Comment by ad-m** [comment]
@daylerees , yes, please.

**Comment by daylerees** [comment]
PR available in : #35 - thanks!

**Comment by ad-m** [comment]
I have to tell you a secret that I'm not a developer's GitHub.

**Comment by jbarnette** [comment]
@ad-m :grinning:
