### ISSUE TITLE
How can we use scientist to do experiment of function has side effect

### ISSUE THREAD

**Issue by m00nlight** [github/scientist#36]
First, thanks for the scientist gems, it really opens my eyes of maintain software reliability. I just have one problem, if the function to test has some side (for example, it query some data in a database and updated it), so if we do run the control and candidate code, it will definitively cause some problem, right?  So is scientist only useful at testing functional style code, or how could we use it to test for function with global side effect?

**Comment by rebyn** [comment]
I guess you figured out, yet for anyone who hasn't gone through all the README, there'a a section for this: https://github.com/github/scientist#designing-an-experiment.
