### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by ZachBeta** [github/scientist#46]
I have some examples of how to use this tool that don't quite fit the README. I was wondering if yall could open up the wiki for additional documentation opportunity. I'd love to put our use case out there for more people to use as a code sample for inspiration.

**Comment by jbarnette** [comment]
@ZachBeta We can probably try enabling the wiki, but how do you feel about a PR adding a Markdown file to a `doc/` or `examples/` directory instead?

**Comment by zeke** [comment]
> adding a Markdown file

I would prefer this :point_up: -- I like watching repo activity, but notifications are not generated for wiki activity.

**Comment by ZachBeta** [comment]
Works for me. I'll put something together and make a PR.

Z

**Comment by jbarnette** [comment]
😎
