### ISSUE TITLE
Some doubts about scientist

### ISSUE THREAD

**Issue by rodrigomonteirof** [github/scientist#48]
Hi Guys,

Sorry if it isnt the best place for doubts, I read the documentation but I not found the answers below:
- How scientist decides when execute the try block?
- How often the try block is executed?
- Does scientist always compare the try with use block?

Thanks

**Comment by zmoazeni** [comment]
I'm new to scientist too, but the Readme addresses each of those questions.

The experiment's `enabled?` method determines whether the try block is attempted. So you have control over when and what frequency. https://github.com/github/scientist/blob/master/README.md#making-science-useful

> Does scientist always compare the try with use block?

It does look like the control and experiment are always compared, but you have control whether you care (`ignore` option) or even finer control if you want to deal with how it's compared (or _when_ if you want to skip the comparisons in certain scenarios).
