### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by lukeasrodgers** [github/scientist#62]
Looks like it's been almost a year since a 1.0.0, and there are some changes (especiallly #58) that would be nice to get into a new release. Obviously I can just use GH master if a release is not feasible at this time.

cheers

**Comment by jbarnette** [comment]
@lukeasrodgers Good idea. I'll see if I can sneak a release in before the holidays. No promises. 😁

**Comment by ericallam** [comment]
Are there any plans on cutting a new release?

**Comment by jbarnette** [comment]
@lukeasrodgers See why I didn't make any promises? 😆 I'm doing some cleanup and prep work now, let's see if I can make this happen!

**Comment by jbarnette** [comment]
After https://github.com/github/scientist/pull/69 lands we should look at a release.

**Comment by jbarnette** [comment]
https://rubygems.org/gems/scientist
